"""Protocol interfaces for SSH, LLM, HA REST, and knowledge store clients."""

from typing import Any, AsyncIterator, Literal, Protocol, Union


class SSHClientProtocol(Protocol):
    async def read_file(self, path: str) -> str: ...

    async def write_file(self, path: str, content: str) -> None: ...

    async def download_file(self, remote_path: str, local_path: str) -> None: ...

    async def run(self, command: str, check: bool = False) -> tuple[int, str, str]: ...

    def stream_lines(self, command: str) -> AsyncIterator[str]: ...


class LLMClientProtocol(Protocol):
    async def chat(
        self,
        model: str,
        messages: list[dict],
        options: dict,
        format: dict,
    ) -> Any: ...

    async def chat_with_tools(
        self,
        model: str,
        messages: list[dict],
        tools: list[dict],
        options: dict | None = None,
        think: Union[bool, Literal["low", "medium", "high"], None] = None,
        keep_alive: int | str | None = None,
    ) -> dict: ...


class HARestClientProtocol(Protocol):
    async def get_states(self, prefix: str | None = None) -> list[dict]: ...

    async def get_state(self, entity_id: str) -> dict: ...

    async def call_service(self, domain: str, service: str, payload: dict) -> dict: ...

    async def get_raw(self, path: str) -> dict: ...

    async def get_text(self, path: str) -> str: ...

    async def post(self, path: str, payload: dict) -> dict: ...

    async def delete(self, path: str) -> None: ...

    async def get_history(self, entity_id: str, hours: float) -> list[dict]: ...

    async def get_logbook(self, entity_id: str, hours: float) -> list[dict]: ...

    async def render_template(self, template: str) -> str: ...

    async def get_services(self) -> list[dict]: ...

    async def get_config_entry_diagnostics(self, entry_id: str) -> dict: ...

    async def reload_config_entry(self, entry_id: str) -> None: ...


class HAWebSocketClientProtocol(Protocol):
    async def get_device_registry(self) -> list[dict]: ...
    async def get_persistent_notifications(self) -> list[dict]: ...
    async def get_repair_issues(self) -> list[dict]: ...
    async def get_config_entries(self) -> list[dict]: ...
    async def get_all_config_entries(self) -> list[dict]: ...
    async def get_ha_components(self) -> list[str]: ...
    async def get_entity_registry(self) -> list[dict]: ...
    async def list_orphaned_database_entities(self) -> dict: ...
    async def get_lovelace_dashboards(self) -> list[dict]: ...
    async def get_lovelace_config(self, url_path: str | None = None) -> dict: ...
    async def get_states(self) -> list[dict]: ...
    async def dismiss_notification(self, notification_id: str) -> None: ...
    async def get_system_log(self) -> list[dict]: ...
    async def get_area_registry(self) -> list[dict]: ...
    async def get_floor_registry(self) -> list[dict]: ...
    async def get_label_registry(self) -> list[dict]: ...
    async def list_traces(
        self, domain: str, item_id: str | None = None
    ) -> list[dict]: ...
    async def get_trace(self, domain: str, item_id: str, run_id: str) -> dict: ...
    async def get_statistics(
        self,
        statistic_ids: list[str],
        start_time: str,
        end_time: str | None,
        period: str,
        types: list[str],
        units: dict | None = None,
    ) -> dict: ...
    async def get_update_release_notes(self, entity_id: str) -> str | None: ...


class HAEventSubscriberProtocol(Protocol):
    def get_events(
        self,
        event_type: str | None,
        entity_id: str | None,
        limit: int,
    ) -> list[dict]: ...

    def is_connected(self) -> bool: ...


class NetAlertXClientProtocol(Protocol):
    async def get_devices(self) -> list[dict]: ...


class KnowledgeStoreClientProtocol(Protocol):
    def upsert(
        self,
        collection: str,
        ids: list[str],
        documents: list[str],
        metadatas: list[dict],
    ) -> None: ...

    def query(
        self,
        query_text: str,
        top_k: int,
        collections: list[str] | None = None,
        where: dict | None = None,
        min_score: float = 0.0,
    ) -> list[Any]: ...

    def prune(self, collection: str, keep_ids: set[str]) -> int: ...

    def total_count(self) -> int: ...
