"""HITL card type constants used by callers and the dashboard dispatch table."""

CARD_TYPE_REPAIR = "repair"
CARD_TYPE_UPDATE = "update"
CARD_TYPE_NETALERTX_HEAL = "netalertx_heal"
CARD_TYPE_NETALERTX_SETUP = "netalertx_setup"
CARD_TYPE_RESOURCE_ACTION = "resource_action"
CARD_TYPE_CODE_PROPOSAL = "code_proposal"
CARD_TYPE_HA_REPAIR = "ha_repair"
CARD_TYPE_CLOUD_ESCALATION = "cloud_escalation"
